# Generated by Django 4.1.7 on 2023-03-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariablesUser2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('i_indent', models.IntegerField()),
                ('bool_tirage_exam', models.BooleanField()),
                ('count_good_answers', models.IntegerField()),
            ],
        ),
    ]
