# Generated by Django 4.1.7 on 2023-03-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_variablesuser2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariablesUser2',
            new_name='VariablesUser',
        ),
    ]
