# Generated by Django 4.1.7 on 2023-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_rename_variablesuser2_variablesuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesuser',
            name='list_q_exam',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
