# Generated by Django 4.1.7 on 2023-03-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_variablesuser_list_q_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
