# Generated by Django 4.1.7 on 2023-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('liste_variable', models.JSONField()),
                ('liste_value', models.JSONField()),
                ('comment', models.TextField(null=True)),
                ('explanation', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.FloatField(null=True)),
                ('given_answer', models.FloatField(blank=True, null=True)),
                ('result', models.BooleanField(null=True)),
            ],
        ),
    ]
