# Generated by Django 4.1.7 on 2023-03-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariablesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('bool_tirage_question', models.BooleanField()),
                ('questions_infos', models.JSONField()),
            ],
        ),
    ]
