# Generated by Django 4.1.7 on 2023-03-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_variablesuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablesuser',
            old_name='questions_infos',
            new_name='question_infos',
        ),
    ]
